#! /bin/bash
#   Doshmajahn
#   Script that looks for if the beacon is running
#   if not it restarts it

search(){
    string="/bin/bash ./digg"
    output=$(ps aux | grep digg)
    if [[ $output == *$string* ]]; then
        echo "running"
    else
        echo "starting back up"
        /bin/bash digg
        echo "started"
    fi
}


main(){
    while true; do
        sleep 10
        search
    done
}

main
